/*
 * Generated by gdbus-codegen 2.48.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "alarmclock_dbus_generated.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface com.time.service.alarmclock
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:alarmClockAlarmclock
 * @title: alarmClockAlarmclock
 * @short_description: Generated C code for the com.time.service.alarmclock D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-time-service-alarmclock.top_of_page">com.time.service.alarmclock</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.time.service.alarmclock ---- */

static const _ExtendedGDBusArgInfo _alarm_clock_alarmclock_method_info_set_time_IN_ARG_currentTime =
{
  {
    -1,
    (gchar *) "currentTime",
    (gchar *) "t",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _alarm_clock_alarmclock_method_info_set_time_IN_ARG_pointers[] =
{
  &_alarm_clock_alarmclock_method_info_set_time_IN_ARG_currentTime,
  NULL
};

static const _ExtendedGDBusMethodInfo _alarm_clock_alarmclock_method_info_set_time =
{
  {
    -1,
    (gchar *) "setTime",
    (GDBusArgInfo **) &_alarm_clock_alarmclock_method_info_set_time_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-time",
  FALSE
};

static const _ExtendedGDBusArgInfo _alarm_clock_alarmclock_method_info_set_alarm_time_IN_ARG_alarmTime =
{
  {
    -1,
    (gchar *) "alarmTime",
    (gchar *) "t",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _alarm_clock_alarmclock_method_info_set_alarm_time_IN_ARG_pointers[] =
{
  &_alarm_clock_alarmclock_method_info_set_alarm_time_IN_ARG_alarmTime,
  NULL
};

static const _ExtendedGDBusMethodInfo _alarm_clock_alarmclock_method_info_set_alarm_time =
{
  {
    -1,
    (gchar *) "setAlarmTime",
    (GDBusArgInfo **) &_alarm_clock_alarmclock_method_info_set_alarm_time_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-alarm-time",
  FALSE
};

static const _ExtendedGDBusArgInfo _alarm_clock_alarmclock_method_info_get_alarm_status_OUT_ARG_status =
{
  {
    -1,
    (gchar *) "status",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _alarm_clock_alarmclock_method_info_get_alarm_status_OUT_ARG_pointers[] =
{
  &_alarm_clock_alarmclock_method_info_get_alarm_status_OUT_ARG_status,
  NULL
};

static const _ExtendedGDBusMethodInfo _alarm_clock_alarmclock_method_info_get_alarm_status =
{
  {
    -1,
    (gchar *) "getAlarmStatus",
    NULL,
    (GDBusArgInfo **) &_alarm_clock_alarmclock_method_info_get_alarm_status_OUT_ARG_pointers,
    NULL
  },
  "handle-get-alarm-status",
  FALSE
};

static const _ExtendedGDBusArgInfo _alarm_clock_alarmclock_method_info_set_alarm_status_IN_ARG_alarmStatus =
{
  {
    -1,
    (gchar *) "alarmStatus",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _alarm_clock_alarmclock_method_info_set_alarm_status_IN_ARG_pointers[] =
{
  &_alarm_clock_alarmclock_method_info_set_alarm_status_IN_ARG_alarmStatus,
  NULL
};

static const _ExtendedGDBusMethodInfo _alarm_clock_alarmclock_method_info_set_alarm_status =
{
  {
    -1,
    (gchar *) "setAlarmStatus",
    (GDBusArgInfo **) &_alarm_clock_alarmclock_method_info_set_alarm_status_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-alarm-status",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _alarm_clock_alarmclock_method_info_pointers[] =
{
  &_alarm_clock_alarmclock_method_info_set_time,
  &_alarm_clock_alarmclock_method_info_set_alarm_time,
  &_alarm_clock_alarmclock_method_info_get_alarm_status,
  &_alarm_clock_alarmclock_method_info_set_alarm_status,
  NULL
};

static const _ExtendedGDBusSignalInfo _alarm_clock_alarmclock_signal_info_ring_alarm =
{
  {
    -1,
    (gchar *) "ringAlarm",
    NULL,
    NULL
  },
  "ring-alarm"
};

static const _ExtendedGDBusSignalInfo * const _alarm_clock_alarmclock_signal_info_pointers[] =
{
  &_alarm_clock_alarmclock_signal_info_ring_alarm,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _alarm_clock_alarmclock_interface_info =
{
  {
    -1,
    (gchar *) "com.time.service.alarmclock",
    (GDBusMethodInfo **) &_alarm_clock_alarmclock_method_info_pointers,
    (GDBusSignalInfo **) &_alarm_clock_alarmclock_signal_info_pointers,
    NULL,
    NULL
  },
  "alarmclock",
};


/**
 * alarm_clock_alarmclock_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-time-service-alarmclock.top_of_page">com.time.service.alarmclock</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
alarm_clock_alarmclock_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_alarm_clock_alarmclock_interface_info.parent_struct;
}

/**
 * alarm_clock_alarmclock_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #alarmClockAlarmclock interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
alarm_clock_alarmclock_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * alarmClockAlarmclock:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-time-service-alarmclock.top_of_page">com.time.service.alarmclock</link>.
 */

/**
 * alarmClockAlarmclockIface:
 * @parent_iface: The parent interface.
 * @handle_get_alarm_status: Handler for the #alarmClockAlarmclock::handle-get-alarm-status signal.
 * @handle_set_alarm_status: Handler for the #alarmClockAlarmclock::handle-set-alarm-status signal.
 * @handle_set_alarm_time: Handler for the #alarmClockAlarmclock::handle-set-alarm-time signal.
 * @handle_set_time: Handler for the #alarmClockAlarmclock::handle-set-time signal.
 * @ring_alarm: Handler for the #alarmClockAlarmclock::ring-alarm signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-time-service-alarmclock.top_of_page">com.time.service.alarmclock</link>.
 */

typedef alarmClockAlarmclockIface alarmClockAlarmclockInterface;
G_DEFINE_INTERFACE (alarmClockAlarmclock, alarm_clock_alarmclock, G_TYPE_OBJECT);

static void
alarm_clock_alarmclock_default_init (alarmClockAlarmclockIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * alarmClockAlarmclock::handle-set-time:
   * @object: A #alarmClockAlarmclock.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_currentTime: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-time-service-alarmclock.setTime">setTime()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call alarm_clock_alarmclock_complete_set_time() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-time",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (alarmClockAlarmclockIface, handle_set_time),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT64);

  /**
   * alarmClockAlarmclock::handle-set-alarm-time:
   * @object: A #alarmClockAlarmclock.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_alarmTime: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-time-service-alarmclock.setAlarmTime">setAlarmTime()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call alarm_clock_alarmclock_complete_set_alarm_time() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-alarm-time",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (alarmClockAlarmclockIface, handle_set_alarm_time),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT64);

  /**
   * alarmClockAlarmclock::handle-get-alarm-status:
   * @object: A #alarmClockAlarmclock.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-time-service-alarmclock.getAlarmStatus">getAlarmStatus()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call alarm_clock_alarmclock_complete_get_alarm_status() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-alarm-status",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (alarmClockAlarmclockIface, handle_get_alarm_status),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * alarmClockAlarmclock::handle-set-alarm-status:
   * @object: A #alarmClockAlarmclock.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_alarmStatus: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-time-service-alarmclock.setAlarmStatus">setAlarmStatus()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call alarm_clock_alarmclock_complete_set_alarm_status() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-alarm-status",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (alarmClockAlarmclockIface, handle_set_alarm_status),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_BOOLEAN);

  /* GObject signals for received D-Bus signals: */
  /**
   * alarmClockAlarmclock::ring-alarm:
   * @object: A #alarmClockAlarmclock.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-com-time-service-alarmclock.ringAlarm">"ringAlarm"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("ring-alarm",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (alarmClockAlarmclockIface, ring_alarm),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    0);

}

/**
 * alarm_clock_alarmclock_emit_ring_alarm:
 * @object: A #alarmClockAlarmclock.
 *
 * Emits the <link linkend="gdbus-signal-com-time-service-alarmclock.ringAlarm">"ringAlarm"</link> D-Bus signal.
 */
void
alarm_clock_alarmclock_emit_ring_alarm (
    alarmClockAlarmclock *object)
{
  g_signal_emit_by_name (object, "ring-alarm");
}

/**
 * alarm_clock_alarmclock_call_set_time:
 * @proxy: A #alarmClockAlarmclockProxy.
 * @arg_currentTime: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-time-service-alarmclock.setTime">setTime()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call alarm_clock_alarmclock_call_set_time_finish() to get the result of the operation.
 *
 * See alarm_clock_alarmclock_call_set_time_sync() for the synchronous, blocking version of this method.
 */
void
alarm_clock_alarmclock_call_set_time (
    alarmClockAlarmclock *proxy,
    guint64 arg_currentTime,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "setTime",
    g_variant_new ("(t)",
                   arg_currentTime),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * alarm_clock_alarmclock_call_set_time_finish:
 * @proxy: A #alarmClockAlarmclockProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to alarm_clock_alarmclock_call_set_time().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with alarm_clock_alarmclock_call_set_time().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
alarm_clock_alarmclock_call_set_time_finish (
    alarmClockAlarmclock *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * alarm_clock_alarmclock_call_set_time_sync:
 * @proxy: A #alarmClockAlarmclockProxy.
 * @arg_currentTime: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-time-service-alarmclock.setTime">setTime()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See alarm_clock_alarmclock_call_set_time() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
alarm_clock_alarmclock_call_set_time_sync (
    alarmClockAlarmclock *proxy,
    guint64 arg_currentTime,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "setTime",
    g_variant_new ("(t)",
                   arg_currentTime),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * alarm_clock_alarmclock_call_set_alarm_time:
 * @proxy: A #alarmClockAlarmclockProxy.
 * @arg_alarmTime: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-time-service-alarmclock.setAlarmTime">setAlarmTime()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call alarm_clock_alarmclock_call_set_alarm_time_finish() to get the result of the operation.
 *
 * See alarm_clock_alarmclock_call_set_alarm_time_sync() for the synchronous, blocking version of this method.
 */
void
alarm_clock_alarmclock_call_set_alarm_time (
    alarmClockAlarmclock *proxy,
    guint64 arg_alarmTime,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "setAlarmTime",
    g_variant_new ("(t)",
                   arg_alarmTime),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * alarm_clock_alarmclock_call_set_alarm_time_finish:
 * @proxy: A #alarmClockAlarmclockProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to alarm_clock_alarmclock_call_set_alarm_time().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with alarm_clock_alarmclock_call_set_alarm_time().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
alarm_clock_alarmclock_call_set_alarm_time_finish (
    alarmClockAlarmclock *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * alarm_clock_alarmclock_call_set_alarm_time_sync:
 * @proxy: A #alarmClockAlarmclockProxy.
 * @arg_alarmTime: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-time-service-alarmclock.setAlarmTime">setAlarmTime()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See alarm_clock_alarmclock_call_set_alarm_time() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
alarm_clock_alarmclock_call_set_alarm_time_sync (
    alarmClockAlarmclock *proxy,
    guint64 arg_alarmTime,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "setAlarmTime",
    g_variant_new ("(t)",
                   arg_alarmTime),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * alarm_clock_alarmclock_call_get_alarm_status:
 * @proxy: A #alarmClockAlarmclockProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-time-service-alarmclock.getAlarmStatus">getAlarmStatus()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call alarm_clock_alarmclock_call_get_alarm_status_finish() to get the result of the operation.
 *
 * See alarm_clock_alarmclock_call_get_alarm_status_sync() for the synchronous, blocking version of this method.
 */
void
alarm_clock_alarmclock_call_get_alarm_status (
    alarmClockAlarmclock *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "getAlarmStatus",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * alarm_clock_alarmclock_call_get_alarm_status_finish:
 * @proxy: A #alarmClockAlarmclockProxy.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to alarm_clock_alarmclock_call_get_alarm_status().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with alarm_clock_alarmclock_call_get_alarm_status().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
alarm_clock_alarmclock_call_get_alarm_status_finish (
    alarmClockAlarmclock *proxy,
    gboolean *out_status,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_status);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * alarm_clock_alarmclock_call_get_alarm_status_sync:
 * @proxy: A #alarmClockAlarmclockProxy.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-time-service-alarmclock.getAlarmStatus">getAlarmStatus()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See alarm_clock_alarmclock_call_get_alarm_status() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
alarm_clock_alarmclock_call_get_alarm_status_sync (
    alarmClockAlarmclock *proxy,
    gboolean *out_status,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "getAlarmStatus",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_status);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * alarm_clock_alarmclock_call_set_alarm_status:
 * @proxy: A #alarmClockAlarmclockProxy.
 * @arg_alarmStatus: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-time-service-alarmclock.setAlarmStatus">setAlarmStatus()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call alarm_clock_alarmclock_call_set_alarm_status_finish() to get the result of the operation.
 *
 * See alarm_clock_alarmclock_call_set_alarm_status_sync() for the synchronous, blocking version of this method.
 */
void
alarm_clock_alarmclock_call_set_alarm_status (
    alarmClockAlarmclock *proxy,
    gboolean arg_alarmStatus,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "setAlarmStatus",
    g_variant_new ("(b)",
                   arg_alarmStatus),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * alarm_clock_alarmclock_call_set_alarm_status_finish:
 * @proxy: A #alarmClockAlarmclockProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to alarm_clock_alarmclock_call_set_alarm_status().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with alarm_clock_alarmclock_call_set_alarm_status().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
alarm_clock_alarmclock_call_set_alarm_status_finish (
    alarmClockAlarmclock *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * alarm_clock_alarmclock_call_set_alarm_status_sync:
 * @proxy: A #alarmClockAlarmclockProxy.
 * @arg_alarmStatus: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-time-service-alarmclock.setAlarmStatus">setAlarmStatus()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See alarm_clock_alarmclock_call_set_alarm_status() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
alarm_clock_alarmclock_call_set_alarm_status_sync (
    alarmClockAlarmclock *proxy,
    gboolean arg_alarmStatus,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "setAlarmStatus",
    g_variant_new ("(b)",
                   arg_alarmStatus),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * alarm_clock_alarmclock_complete_set_time:
 * @object: A #alarmClockAlarmclock.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-time-service-alarmclock.setTime">setTime()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
alarm_clock_alarmclock_complete_set_time (
    alarmClockAlarmclock *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * alarm_clock_alarmclock_complete_set_alarm_time:
 * @object: A #alarmClockAlarmclock.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-time-service-alarmclock.setAlarmTime">setAlarmTime()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
alarm_clock_alarmclock_complete_set_alarm_time (
    alarmClockAlarmclock *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * alarm_clock_alarmclock_complete_get_alarm_status:
 * @object: A #alarmClockAlarmclock.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @status: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-time-service-alarmclock.getAlarmStatus">getAlarmStatus()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
alarm_clock_alarmclock_complete_get_alarm_status (
    alarmClockAlarmclock *object,
    GDBusMethodInvocation *invocation,
    gboolean status)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   status));
}

/**
 * alarm_clock_alarmclock_complete_set_alarm_status:
 * @object: A #alarmClockAlarmclock.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-time-service-alarmclock.setAlarmStatus">setAlarmStatus()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
alarm_clock_alarmclock_complete_set_alarm_status (
    alarmClockAlarmclock *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * alarmClockAlarmclockProxy:
 *
 * The #alarmClockAlarmclockProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * alarmClockAlarmclockProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #alarmClockAlarmclockProxy.
 */

struct _alarmClockAlarmclockProxyPrivate
{
  GData *qdata;
};

static void alarm_clock_alarmclock_proxy_iface_init (alarmClockAlarmclockIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (alarmClockAlarmclockProxy, alarm_clock_alarmclock_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (alarmClockAlarmclockProxy)
                         G_IMPLEMENT_INTERFACE (ALARM_CLOCK_TYPE_ALARMCLOCK, alarm_clock_alarmclock_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (alarmClockAlarmclockProxy, alarm_clock_alarmclock_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (ALARM_CLOCK_TYPE_ALARMCLOCK, alarm_clock_alarmclock_proxy_iface_init));

#endif
static void
alarm_clock_alarmclock_proxy_finalize (GObject *object)
{
  alarmClockAlarmclockProxy *proxy = ALARM_CLOCK_ALARMCLOCK_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (alarm_clock_alarmclock_proxy_parent_class)->finalize (object);
}

static void
alarm_clock_alarmclock_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
alarm_clock_alarmclock_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
alarm_clock_alarmclock_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_alarm_clock_alarmclock_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], ALARM_CLOCK_TYPE_ALARMCLOCK);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, ALARM_CLOCK_TYPE_ALARMCLOCK);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
alarm_clock_alarmclock_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  alarmClockAlarmclockProxy *proxy = ALARM_CLOCK_ALARMCLOCK_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_alarm_clock_alarmclock_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_alarm_clock_alarmclock_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
alarm_clock_alarmclock_proxy_init (alarmClockAlarmclockProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = alarm_clock_alarmclock_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, ALARM_CLOCK_TYPE_ALARMCLOCK_PROXY, alarmClockAlarmclockProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), alarm_clock_alarmclock_interface_info ());
}

static void
alarm_clock_alarmclock_proxy_class_init (alarmClockAlarmclockProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = alarm_clock_alarmclock_proxy_finalize;
  gobject_class->get_property = alarm_clock_alarmclock_proxy_get_property;
  gobject_class->set_property = alarm_clock_alarmclock_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = alarm_clock_alarmclock_proxy_g_signal;
  proxy_class->g_properties_changed = alarm_clock_alarmclock_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (alarmClockAlarmclockProxyPrivate));
#endif
}

static void
alarm_clock_alarmclock_proxy_iface_init (alarmClockAlarmclockIface *iface)
{
}

/**
 * alarm_clock_alarmclock_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-time-service-alarmclock.top_of_page">com.time.service.alarmclock</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call alarm_clock_alarmclock_proxy_new_finish() to get the result of the operation.
 *
 * See alarm_clock_alarmclock_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
alarm_clock_alarmclock_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (ALARM_CLOCK_TYPE_ALARMCLOCK_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.time.service.alarmclock", NULL);
}

/**
 * alarm_clock_alarmclock_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to alarm_clock_alarmclock_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with alarm_clock_alarmclock_proxy_new().
 *
 * Returns: (transfer full) (type alarmClockAlarmclockProxy): The constructed proxy object or %NULL if @error is set.
 */
alarmClockAlarmclock *
alarm_clock_alarmclock_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return ALARM_CLOCK_ALARMCLOCK (ret);
  else
    return NULL;
}

/**
 * alarm_clock_alarmclock_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-time-service-alarmclock.top_of_page">com.time.service.alarmclock</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See alarm_clock_alarmclock_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type alarmClockAlarmclockProxy): The constructed proxy object or %NULL if @error is set.
 */
alarmClockAlarmclock *
alarm_clock_alarmclock_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (ALARM_CLOCK_TYPE_ALARMCLOCK_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.time.service.alarmclock", NULL);
  if (ret != NULL)
    return ALARM_CLOCK_ALARMCLOCK (ret);
  else
    return NULL;
}


/**
 * alarm_clock_alarmclock_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like alarm_clock_alarmclock_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call alarm_clock_alarmclock_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See alarm_clock_alarmclock_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
alarm_clock_alarmclock_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (ALARM_CLOCK_TYPE_ALARMCLOCK_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.time.service.alarmclock", NULL);
}

/**
 * alarm_clock_alarmclock_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to alarm_clock_alarmclock_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with alarm_clock_alarmclock_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type alarmClockAlarmclockProxy): The constructed proxy object or %NULL if @error is set.
 */
alarmClockAlarmclock *
alarm_clock_alarmclock_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return ALARM_CLOCK_ALARMCLOCK (ret);
  else
    return NULL;
}

/**
 * alarm_clock_alarmclock_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like alarm_clock_alarmclock_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See alarm_clock_alarmclock_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type alarmClockAlarmclockProxy): The constructed proxy object or %NULL if @error is set.
 */
alarmClockAlarmclock *
alarm_clock_alarmclock_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (ALARM_CLOCK_TYPE_ALARMCLOCK_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.time.service.alarmclock", NULL);
  if (ret != NULL)
    return ALARM_CLOCK_ALARMCLOCK (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * alarmClockAlarmclockSkeleton:
 *
 * The #alarmClockAlarmclockSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * alarmClockAlarmclockSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #alarmClockAlarmclockSkeleton.
 */

struct _alarmClockAlarmclockSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_alarm_clock_alarmclock_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  alarmClockAlarmclockSkeleton *skeleton = ALARM_CLOCK_ALARMCLOCK_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], ALARM_CLOCK_TYPE_ALARMCLOCK);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, ALARM_CLOCK_TYPE_ALARMCLOCK);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_alarm_clock_alarmclock_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  alarmClockAlarmclockSkeleton *skeleton = ALARM_CLOCK_ALARMCLOCK_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_alarm_clock_alarmclock_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_alarm_clock_alarmclock_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  alarmClockAlarmclockSkeleton *skeleton = ALARM_CLOCK_ALARMCLOCK_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_alarm_clock_alarmclock_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _alarm_clock_alarmclock_skeleton_vtable =
{
  _alarm_clock_alarmclock_skeleton_handle_method_call,
  _alarm_clock_alarmclock_skeleton_handle_get_property,
  _alarm_clock_alarmclock_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
alarm_clock_alarmclock_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return alarm_clock_alarmclock_interface_info ();
}

static GDBusInterfaceVTable *
alarm_clock_alarmclock_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_alarm_clock_alarmclock_skeleton_vtable;
}

static GVariant *
alarm_clock_alarmclock_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  alarmClockAlarmclockSkeleton *skeleton = ALARM_CLOCK_ALARMCLOCK_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_alarm_clock_alarmclock_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _alarm_clock_alarmclock_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _alarm_clock_alarmclock_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _alarm_clock_alarmclock_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.time.service.alarmclock", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
alarm_clock_alarmclock_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_alarm_clock_alarmclock_on_signal_ring_alarm (
    alarmClockAlarmclock *object)
{
  alarmClockAlarmclockSkeleton *skeleton = ALARM_CLOCK_ALARMCLOCK_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("()"));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.time.service.alarmclock", "ringAlarm",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void alarm_clock_alarmclock_skeleton_iface_init (alarmClockAlarmclockIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (alarmClockAlarmclockSkeleton, alarm_clock_alarmclock_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (alarmClockAlarmclockSkeleton)
                         G_IMPLEMENT_INTERFACE (ALARM_CLOCK_TYPE_ALARMCLOCK, alarm_clock_alarmclock_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (alarmClockAlarmclockSkeleton, alarm_clock_alarmclock_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (ALARM_CLOCK_TYPE_ALARMCLOCK, alarm_clock_alarmclock_skeleton_iface_init));

#endif
static void
alarm_clock_alarmclock_skeleton_finalize (GObject *object)
{
  alarmClockAlarmclockSkeleton *skeleton = ALARM_CLOCK_ALARMCLOCK_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (alarm_clock_alarmclock_skeleton_parent_class)->finalize (object);
}

static void
alarm_clock_alarmclock_skeleton_init (alarmClockAlarmclockSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = alarm_clock_alarmclock_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, ALARM_CLOCK_TYPE_ALARMCLOCK_SKELETON, alarmClockAlarmclockSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
alarm_clock_alarmclock_skeleton_class_init (alarmClockAlarmclockSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = alarm_clock_alarmclock_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = alarm_clock_alarmclock_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = alarm_clock_alarmclock_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = alarm_clock_alarmclock_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = alarm_clock_alarmclock_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (alarmClockAlarmclockSkeletonPrivate));
#endif
}

static void
alarm_clock_alarmclock_skeleton_iface_init (alarmClockAlarmclockIface *iface)
{
  iface->ring_alarm = _alarm_clock_alarmclock_on_signal_ring_alarm;
}

/**
 * alarm_clock_alarmclock_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-time-service-alarmclock.top_of_page">com.time.service.alarmclock</link>.
 *
 * Returns: (transfer full) (type alarmClockAlarmclockSkeleton): The skeleton object.
 */
alarmClockAlarmclock *
alarm_clock_alarmclock_skeleton_new (void)
{
  return ALARM_CLOCK_ALARMCLOCK (g_object_new (ALARM_CLOCK_TYPE_ALARMCLOCK_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for Object, ObjectProxy and ObjectSkeleton
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:alarmClockObject
 * @title: alarmClockObject
 * @short_description: Specialized GDBusObject types
 *
 * This section contains the #alarmClockObject, #alarmClockObjectProxy, and #alarmClockObjectSkeleton types which make it easier to work with objects implementing generated types for D-Bus interfaces.
 */

/**
 * alarmClockObject:
 *
 * The #alarmClockObject type is a specialized container of interfaces.
 */

/**
 * alarmClockObjectIface:
 * @parent_iface: The parent interface.
 *
 * Virtual table for the #alarmClockObject interface.
 */

typedef alarmClockObjectIface alarmClockObjectInterface;
G_DEFINE_INTERFACE_WITH_CODE (alarmClockObject, alarm_clock_object, G_TYPE_OBJECT, g_type_interface_add_prerequisite (g_define_type_id, G_TYPE_DBUS_OBJECT));

static void
alarm_clock_object_default_init (alarmClockObjectIface *iface)
{
  /**
   * alarmClockObject:alarmclock:
   *
   * The #alarmClockAlarmclock instance corresponding to the D-Bus interface <link linkend="gdbus-interface-com-time-service-alarmclock.top_of_page">com.time.service.alarmclock</link>, if any.
   *
   * Connect to the #GObject::notify signal to get informed of property changes.
   */
  g_object_interface_install_property (iface, g_param_spec_object ("alarmclock", "alarmclock", "alarmclock", ALARM_CLOCK_TYPE_ALARMCLOCK, G_PARAM_READWRITE|G_PARAM_STATIC_STRINGS));

}

/**
 * alarm_clock_object_get_alarmclock:
 * @object: A #alarmClockObject.
 *
 * Gets the #alarmClockAlarmclock instance for the D-Bus interface <link linkend="gdbus-interface-com-time-service-alarmclock.top_of_page">com.time.service.alarmclock</link> on @object, if any.
 *
 * Returns: (transfer full): A #alarmClockAlarmclock that must be freed with g_object_unref() or %NULL if @object does not implement the interface.
 */
alarmClockAlarmclock *alarm_clock_object_get_alarmclock (alarmClockObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "com.time.service.alarmclock");
  if (ret == NULL)
    return NULL;
  return ALARM_CLOCK_ALARMCLOCK (ret);
}


/**
 * alarm_clock_object_peek_alarmclock: (skip)
 * @object: A #alarmClockObject.
 *
 * Like alarm_clock_object_get_alarmclock() but doesn't increase the reference count on the returned object.
 *
 * <warning>It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.</warning>
 *
 * Returns: (transfer none): A #alarmClockAlarmclock or %NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
 */
alarmClockAlarmclock *alarm_clock_object_peek_alarmclock (alarmClockObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "com.time.service.alarmclock");
  if (ret == NULL)
    return NULL;
  g_object_unref (ret);
  return ALARM_CLOCK_ALARMCLOCK (ret);
}


static void
alarm_clock_object_notify (GDBusObject *object, GDBusInterface *interface)
{
  _ExtendedGDBusInterfaceInfo *info = (_ExtendedGDBusInterfaceInfo *) g_dbus_interface_get_info (interface);
  /* info can be NULL if the other end is using a D-Bus interface we don't know
   * anything about, for example old generated code in this process talking to
   * newer generated code in the other process. */
  if (info != NULL)
    g_object_notify (G_OBJECT (object), info->hyphen_name);
}

/**
 * alarmClockObjectProxy:
 *
 * The #alarmClockObjectProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * alarmClockObjectProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #alarmClockObjectProxy.
 */

static void
alarm_clock_object_proxy__alarm_clock_object_iface_init (alarmClockObjectIface *iface G_GNUC_UNUSED)
{
}

static void
alarm_clock_object_proxy__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = alarm_clock_object_notify;
  iface->interface_removed = alarm_clock_object_notify;
}


G_DEFINE_TYPE_WITH_CODE (alarmClockObjectProxy, alarm_clock_object_proxy, G_TYPE_DBUS_OBJECT_PROXY,
                         G_IMPLEMENT_INTERFACE (ALARM_CLOCK_TYPE_OBJECT, alarm_clock_object_proxy__alarm_clock_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, alarm_clock_object_proxy__g_dbus_object_iface_init));

static void
alarm_clock_object_proxy_init (alarmClockObjectProxy *object G_GNUC_UNUSED)
{
}

static void
alarm_clock_object_proxy_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value G_GNUC_UNUSED,
  GParamSpec   *pspec)
{
  G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
}

static void
alarm_clock_object_proxy_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  alarmClockObjectProxy *object = ALARM_CLOCK_OBJECT_PROXY (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "com.time.service.alarmclock");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
alarm_clock_object_proxy_class_init (alarmClockObjectProxyClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = alarm_clock_object_proxy_set_property;
  gobject_class->get_property = alarm_clock_object_proxy_get_property;

  g_object_class_override_property (gobject_class, 1, "alarmclock");
}

/**
 * alarm_clock_object_proxy_new:
 * @connection: A #GDBusConnection.
 * @object_path: An object path.
 *
 * Creates a new proxy object.
 *
 * Returns: (transfer full): The proxy object.
 */
alarmClockObjectProxy *
alarm_clock_object_proxy_new (GDBusConnection *connection,
  const gchar *object_path)
{
  g_return_val_if_fail (G_IS_DBUS_CONNECTION (connection), NULL);
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return ALARM_CLOCK_OBJECT_PROXY (g_object_new (ALARM_CLOCK_TYPE_OBJECT_PROXY, "g-connection", connection, "g-object-path", object_path, NULL));
}

/**
 * alarmClockObjectSkeleton:
 *
 * The #alarmClockObjectSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * alarmClockObjectSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #alarmClockObjectSkeleton.
 */

static void
alarm_clock_object_skeleton__alarm_clock_object_iface_init (alarmClockObjectIface *iface G_GNUC_UNUSED)
{
}


static void
alarm_clock_object_skeleton__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = alarm_clock_object_notify;
  iface->interface_removed = alarm_clock_object_notify;
}

G_DEFINE_TYPE_WITH_CODE (alarmClockObjectSkeleton, alarm_clock_object_skeleton, G_TYPE_DBUS_OBJECT_SKELETON,
                         G_IMPLEMENT_INTERFACE (ALARM_CLOCK_TYPE_OBJECT, alarm_clock_object_skeleton__alarm_clock_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, alarm_clock_object_skeleton__g_dbus_object_iface_init));

static void
alarm_clock_object_skeleton_init (alarmClockObjectSkeleton *object G_GNUC_UNUSED)
{
}

static void
alarm_clock_object_skeleton_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  alarmClockObjectSkeleton *object = ALARM_CLOCK_OBJECT_SKELETON (gobject);
  GDBusInterfaceSkeleton *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_value_get_object (value);
      if (interface != NULL)
        {
          g_warn_if_fail (ALARM_CLOCK_IS_ALARMCLOCK (interface));
          g_dbus_object_skeleton_add_interface (G_DBUS_OBJECT_SKELETON (object), interface);
        }
      else
        {
          g_dbus_object_skeleton_remove_interface_by_name (G_DBUS_OBJECT_SKELETON (object), "com.time.service.alarmclock");
        }
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
alarm_clock_object_skeleton_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  alarmClockObjectSkeleton *object = ALARM_CLOCK_OBJECT_SKELETON (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "com.time.service.alarmclock");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
alarm_clock_object_skeleton_class_init (alarmClockObjectSkeletonClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = alarm_clock_object_skeleton_set_property;
  gobject_class->get_property = alarm_clock_object_skeleton_get_property;

  g_object_class_override_property (gobject_class, 1, "alarmclock");
}

/**
 * alarm_clock_object_skeleton_new:
 * @object_path: An object path.
 *
 * Creates a new skeleton object.
 *
 * Returns: (transfer full): The skeleton object.
 */
alarmClockObjectSkeleton *
alarm_clock_object_skeleton_new (const gchar *object_path)
{
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return ALARM_CLOCK_OBJECT_SKELETON (g_object_new (ALARM_CLOCK_TYPE_OBJECT_SKELETON, "g-object-path", object_path, NULL));
}

/**
 * alarm_clock_object_skeleton_set_alarmclock:
 * @object: A #alarmClockObjectSkeleton.
 * @interface_: (allow-none): A #alarmClockAlarmclock or %NULL to clear the interface.
 *
 * Sets the #alarmClockAlarmclock instance for the D-Bus interface <link linkend="gdbus-interface-com-time-service-alarmclock.top_of_page">com.time.service.alarmclock</link> on @object.
 */
void alarm_clock_object_skeleton_set_alarmclock (alarmClockObjectSkeleton *object, alarmClockAlarmclock *interface_)
{
  g_object_set (G_OBJECT (object), "alarmclock", interface_, NULL);
}


/* ------------------------------------------------------------------------
 * Code for ObjectManager client
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:alarmClockObjectManagerClient
 * @title: alarmClockObjectManagerClient
 * @short_description: Generated GDBusObjectManagerClient type
 *
 * This section contains a #GDBusObjectManagerClient that uses alarm_clock_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc.
 */

/**
 * alarmClockObjectManagerClient:
 *
 * The #alarmClockObjectManagerClient structure contains only private data and should only be accessed using the provided API.
 */

/**
 * alarmClockObjectManagerClientClass:
 * @parent_class: The parent class.
 *
 * Class structure for #alarmClockObjectManagerClient.
 */

G_DEFINE_TYPE (alarmClockObjectManagerClient, alarm_clock_object_manager_client, G_TYPE_DBUS_OBJECT_MANAGER_CLIENT);

static void
alarm_clock_object_manager_client_init (alarmClockObjectManagerClient *manager G_GNUC_UNUSED)
{
}

static void
alarm_clock_object_manager_client_class_init (alarmClockObjectManagerClientClass *klass G_GNUC_UNUSED)
{
}

/**
 * alarm_clock_object_manager_client_get_proxy_type:
 * @manager: A #GDBusObjectManagerClient.
 * @object_path: The object path of the remote object (unused).
 * @interface_name: (allow-none): Interface name of the remote object or %NULL to get the object proxy #GType.
 * @user_data: User data (unused).
 *
 * A #GDBusProxyTypeFunc that maps @interface_name to the generated #GDBusObjectProxy<!-- -->- and #GDBusProxy<!-- -->-derived types.
 *
 * Returns: A #GDBusProxy<!-- -->-derived #GType if @interface_name is not %NULL, otherwise the #GType for #alarmClockObjectProxy.
 */
GType
alarm_clock_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager G_GNUC_UNUSED, const gchar *object_path G_GNUC_UNUSED, const gchar *interface_name, gpointer user_data G_GNUC_UNUSED)
{
  static gsize once_init_value = 0;
  static GHashTable *lookup_hash;
  GType ret;

  if (interface_name == NULL)
    return ALARM_CLOCK_TYPE_OBJECT_PROXY;
  if (g_once_init_enter (&once_init_value))
    {
      lookup_hash = g_hash_table_new (g_str_hash, g_str_equal);
      g_hash_table_insert (lookup_hash, (gpointer) "com.time.service.alarmclock", GSIZE_TO_POINTER (ALARM_CLOCK_TYPE_ALARMCLOCK_PROXY));
      g_once_init_leave (&once_init_value, 1);
    }
  ret = (GType) GPOINTER_TO_SIZE (g_hash_table_lookup (lookup_hash, interface_name));
  if (ret == (GType) 0)
    ret = G_TYPE_DBUS_PROXY;
  return ret;
}

/**
 * alarm_clock_object_manager_client_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates #GDBusObjectManagerClient using alarm_clock_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call alarm_clock_object_manager_client_new_finish() to get the result of the operation.
 *
 * See alarm_clock_object_manager_client_new_sync() for the synchronous, blocking version of this constructor.
 */
void
alarm_clock_object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (ALARM_CLOCK_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", alarm_clock_object_manager_client_get_proxy_type, NULL);
}

/**
 * alarm_clock_object_manager_client_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to alarm_clock_object_manager_client_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with alarm_clock_object_manager_client_new().
 *
 * Returns: (transfer full) (type alarmClockObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
alarm_clock_object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * alarm_clock_object_manager_client_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates #GDBusObjectManagerClient using alarm_clock_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See alarm_clock_object_manager_client_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type alarmClockObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
alarm_clock_object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (ALARM_CLOCK_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", alarm_clock_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


/**
 * alarm_clock_object_manager_client_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like alarm_clock_object_manager_client_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call alarm_clock_object_manager_client_new_for_bus_finish() to get the result of the operation.
 *
 * See alarm_clock_object_manager_client_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
alarm_clock_object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (ALARM_CLOCK_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", alarm_clock_object_manager_client_get_proxy_type, NULL);
}

/**
 * alarm_clock_object_manager_client_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to alarm_clock_object_manager_client_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with alarm_clock_object_manager_client_new_for_bus().
 *
 * Returns: (transfer full) (type alarmClockObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
alarm_clock_object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * alarm_clock_object_manager_client_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like alarm_clock_object_manager_client_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See alarm_clock_object_manager_client_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type alarmClockObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
alarm_clock_object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (ALARM_CLOCK_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", alarm_clock_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


